#!/bin/sh
envdir=$PWD/env
root=$(<env/TCC_Root)
echo Home is $HOME
echo Starting from $root
cd $root
rbenv=$HOME/.rvm/scripts/rvm
if [ -s "$rbenv" ];then
  echo "Sourcing $rbenv"
  source "$rbenv"
  echo "Using RVM $(which rvm)"
  source $root/.rvmrc.tcc  
fi
exec chpst -e $envdir ./bin/queue_router 2>&1
