#!/bin/bash -e
envdir=$PWD/env
root=$(<env/TCC_Root)
echo Starting from $root
cd $root
if [ -s $HOME/.rvm/scripts/rvm ]; then
  source $HOME/.rvm/scripts/rvm
  echo "Using RVM $(which rvm)"
  rvm use 1.9.2 2>&1
  source .rvmrc.tcc
fi
exec chpst -e $envdir bin/fs2ws 2>&1
